name: Gradle Package

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        
    - run: chmod +x ./gradlew
    
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build & Publish package
      run: ./gradlew --no-daemon -Prevision=${{ github.sha }} build publish
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
